# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMylbTlzFA2ONoW94oMMMtDpph5OzNsr
"""

# =======================================================
#   PROGRAM SISTEM ORGANISASI SEKOLAH (Sederhana)
# =======================================================

organisasi_sekolah = {
    "OSIS": [],
    "Pramuka": [],
    "PMR": [],
    "Paskibra": [],
    "Rohis": [],
    "Banjari": [],
    "Basket": [],
    "PIK-R": [],
    "PKS": [],
    "Vokal": [],
}

def garis():
    print("="*55)

def tampilkan_organisasi():
    garis()
    print("DAFTAR ORGANISASI DI SMA ! PLOSOKLATEN")
    garis()
    for org in organisasi_sekolah:
        print(f"- {org}")
    garis()


def tambah_organisasi():
    garis()
    nama = input("Nama organisasi baru: ").strip()
    if nama in organisasi_sekolah:
        print("Organisasi sudah terdaftar!")
    else:
        organisasi_sekolah[nama] = []
        print(f"Organisasi '{nama}' berhasil ditambahkan!")
    garis()


def hapus_organisasi():
    tampilkan_organisasi()
    nama = input("Masukkan nama organisasi yang ingin dihapus: ").strip()
    if nama in organisasi_sekolah:
        del organisasi_sekolah[nama]
        print(f"Organisasi '{nama}' berhasil dihapus!")
    else:
        print("Organisasi tidak ditemukan!")
    garis()


def tambah_anggota():
    tampilkan_organisasi()
    nama_org = input("Pilih organisasi: ").strip()

    if nama_org not in organisasi_sekolah:
        print("Organisasi tidak ditemukan!")
        return

    anggota = input("Nama anggota baru: ").strip()
    organisasi_sekolah[nama_org].append(anggota)
    print(f"Anggota '{anggota}' berhasil ditambahkan ke {nama_org}!")
    garis()


def tampilkan_anggota():
    tampilkan_organisasi()
    nama_org = input("Pilih organisasi untuk melihat anggotanya: ").strip()

    if nama_org not in organisasi_sekolah:
        print("Organisasi tidak ditemukan!")
        return

    garis()
    print(f"DAFTAR ANGGOTA {nama_org}")
    garis()

    if len(organisasi_sekolah[nama_org]) == 0:
        print("(Belum ada anggota)")
    else:
        for a in organisasi_sekolah[nama_org]:
            print(f"- {a}")
    garis()


def menu():
    while True:
        garis()
        print("SISTEM ORGANISASI SEKOLAH")
        garis()
        print("""
1. Tampilkan daftar organisasi
2. Tambah organisasi baru
3. Hapus organisasi
4. Tambah anggota ke organisasi
5. Tampilkan anggota suatu organisasi
0. Keluar
""")
        garis()
        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            tampilkan_organisasi()

        elif pilihan == "2":
            tambah_organisasi()

        elif pilihan == "3":
            hapus_organisasi()

        elif pilihan == "4":
            tambah_anggota()

        elif pilihan == "5":
            tampilkan_anggota()

        elif pilihan == "0":
            print("Program selesai. Terima kasih!")
            break

        else:
            print("Pilihan tidak valid! Coba lagi.\n")


# Jalankan program
menu()